-- 코드를 입력하세요
SELECT A.AUTHOR_ID,
       B.AUTHOR_NAME,
       A.CATEGORY,
       SUM(C.SALES * A.PRICE) TOTAL_SALES
FROM BOOK A, AUTHOR B, BOOK_SALES C
WHERE TO_CHAR(C.SALES_DATE, 'YYYY-MM-DD') LIKE '2022-01%'
  AND A.BOOK_ID = C.BOOK_ID
  AND A.AUTHOR_ID = B.AUTHOR_ID
GROUP BY A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC;