-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME FROM (
SELECT A.ANIMAL_ID, A.NAME, B.DATETIME - A.DATETIME AS DIFF
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DIFF DESC)
WHERE ROWNUM <= 2;