-- 코드를 입력하세요
SELECT CAR_ID,
       CAR_TYPE,
       ROUND((DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100))) AS FEE
FROM (
SELECT DISTINCT A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, C.DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_CAR A, CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
WHERE A.CAR_TYPE IN ('SUV', '세단')
  AND C.CAR_TYPE = A.CAR_TYPE
  AND C.DURATION_TYPE LIKE '30%'
  AND (A.CAR_ID IN (SELECT CAR_ID FROM (
             SELECT CAR_ID, MAX(START_DATE) AS ST, MAX(END_DATE) AS ED
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
           GROUP BY CAR_ID)
                     WHERE ST > TO_DATE('20221201', 'YYYYMMDD')
                       OR ED < TO_DATE('20221101', 'YYYYMMDD'))
       OR A.CAR_ID NOT IN (SELECT DISTINCT CAR_ID
                             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)))
WHERE ROUND((DAILY_FEE * 30 * (1 - DISCOUNT_RATE / 100))) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;