-- 코드를 입력하세요
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A, (SELECT FOOD_TYPE, MAX(FAVORITES) AS MX
                     FROM REST_INFO
                 GROUP BY FOOD_TYPE) B
WHERE A.FOOD_TYPE = B.FOOD_TYPE AND A.FAVORITES = B.MX
ORDER BY A.FOOD_TYPE DESC;