-- 코드를 입력하세요
WITH TOTAL_CNT AS
    (SELECT COUNT(USER_ID) AS TOTAL_CNT
    FROM USER_INFO
    WHERE JOINED BETWEEN TO_DATE('20210101','YYYYMMDD')
    AND TO_DATE('20211231','YYYYMMDD')),
    USERS AS
    (SELECT USER_ID
       FROM USER_INFO
      WHERE JOINED BETWEEN TO_DATE('20210101','YYYYMMDD')
                       AND TO_DATE('20211231','YYYYMMDD'))

SELECT YEAR, TO_NUMBER(MONTH) AS MONTH,
       PURCHASED_USERS,
       ROUND(PURCHASED_USERS / (SELECT * FROM TOTAL_CNT), 1) AS PUCHASED_RATIO
FROM (
SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR,
       TO_CHAR(SALES_DATE, 'MM') AS MONTH,
       COUNT(DISTINCT USER_ID) AS PURCHASED_USERS
FROM (SELECT B.USER_ID, B.SALES_DATE
        FROM USER_INFO A, ONLINE_SALE B
       WHERE B.USER_ID IN (SELECT * FROM USERS))
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'),
         TO_CHAR(SALES_DATE, 'MM')
    )
ORDER BY YEAR, MONTH