-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE * B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCE_DATE BETWEEN TO_DATE('20220501', 'YYYYMMDD')
                         AND TO_DATE('20220531', 'YYYYMMDD')
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY 3 DESC, 1 ASC;