-- 코드를 입력하세요
SELECT HISTORY_ID,
       FEE * (1 - B.DISCOUNT_RATE / 100) AS FEE
FROM (SELECT B.HISTORY_ID,
            (B.END_DATE - B.START_DATE + 1) * A.DAILY_FEE AS FEE,
             CASE WHEN B.END_DATE - B.START_DATE + 1 >= 90 THEN 90
                  WHEN B.END_DATE - B.START_DATE + 1 >= 30 THEN 30
                  WHEN B.END_DATE - B.START_DATE + 1 >= 7 THEN 7
                  ELSE 0 END AS TYPE
        FROM CAR_RENTAL_COMPANY_CAR A,
             CAR_RENTAL_COMPANY_RENTAL_HISTORY B
       WHERE A.CAR_TYPE = '트럭'
         AND A.CAR_ID = B.CAR_ID) A,
     (SELECT TO_NUMBER(SUBSTR(DURATION_TYPE, 0, INSTR(DURATION_TYPE, '일') - 1)) AS DURATION_TYPE,
             DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
       WHERE CAR_TYPE = '트럭'
   UNION ALL
      SELECT 0 AS DURATION_TYPE, 0 AS DISCOUNT_RATE FROM DUAL) B
WHERE A.TYPE = B.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;