-- 코드를 입력하세요
SELECT FLAVOR
  FROM (SELECT A.FLAVOR, (A.TOTAL_ORDER + B.JO) AS TOTAL_ORDER
          FROM FIRST_HALF A JOIN
               (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JO
                  FROM JULY GROUP BY FLAVOR) B
            ON A.FLAVOR = B.FLAVOR
      ORDER BY 2 DESC)
FETCH FIRST 3 ROWS ONLY;