-- 코드를 입력하세요
SELECT C.APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, B.DR_NAME, C.APNT_YMD
FROM PATIENT A, DOCTOR B, APPOINTMENT C
WHERE TO_CHAR(C.APNT_YMD, 'YYYYMMDD') = '20220413'
AND C.APNT_CNCL_YN = 'N'
AND C.MCDP_CD = 'CS'
AND C.PT_NO = A.PT_NO
AND C.MDDR_ID = B.DR_ID
ORDER BY C.APNT_YMD ASC;