-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE SUBSTR(TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD'), 7, 1) = '3'
AND GENDER = 'W'
AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;