-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A,
     CAR_RENTAL_COMPANY_RENTAL_HISTORY B
WHERE A.CAR_ID = B.CAR_ID
  AND A.CAR_TYPE = '세단'
  AND B.START_DATE BETWEEN TO_DATE('20221001', 'YYYYMMDD') AND TO_DATE('20221031', 'YYYYMMDD')
ORDER BY A.CAR_ID DESC;