-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A, (SELECT CATEGORY, MAX(PRICE) AS MX
                        FROM FOOD_PRODUCT
                       WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
                    GROUP BY CATEGORY) B
WHERE A.CATEGORY = B.CATEGORY AND A.PRICE = B.MX
ORDER BY PRICE DESC;